# Generated by Django 3.0.7 on 2021-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null='True', upload_to='productos'),
            preserve_default='True',
        ),
    ]
