# Generated by Django 3.2.7 on 2021-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(auto_now=True),
        ),
    ]
