# Generated by Django 3.2.6 on 2021-09-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_producto_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marca',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='categoria',
        ),
    ]
